name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: mdBook Action
        uses: peaceiris/actions-mdbook@v1.1.13
        with:
          mdbook-version: 'latest'

      - name: Build ems-docs
	run: ldd --version
        run: mdbook build

      - name: Build ee-installer
        run: cd ./ee-installer && mdbook build && cd ../

      - name: Copy ee-installer into document root
        run: mkdir ./book/ee-installer && cp -R ./ee-installer/book/* ./book/ee-installer/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
